export const searchableSections: { tab: string; title: string; keywords: string[] }[] = [
  { tab: 'node', title: 'Node Infrastructure', keywords: ['node', 'sync', 'status', 'tip', 'slot', 'height', 'infrastructure', 'kupo', 'indexer'] },
  { tab: 'node', title: 'Processes', keywords: ['process', 'pid', 'restart', 'ogmios', 'kupo', 'express', 'cardano', 'mithril'] },
  { tab: 'wallet', title: 'Wallet Info', keywords: ['wallet', 'address', 'balance', 'ada', 'copy'] },
  { tab: 'wallet', title: 'Wallet Management', keywords: ['wallet', 'collateral', 'defrag', 'optimize', 'utxo', 'fragment', 'consolidate', 'analyze', 'health'] },
  { tab: 'wallet', title: 'Recovery Phrase', keywords: ['recovery', 'phrase', 'mnemonic', 'seed', 'backup', 'reveal'] },
  { tab: 'preferences', title: 'Language', keywords: ['language', 'locale', 'i18n', 'translation', 'english'] },
  { tab: 'preferences', title: 'Theme', keywords: ['theme', 'dark', 'light', 'mode', 'appearance', 'color', 'system', 'auto', 'os', 'prefer'] },
  { tab: 'preferences', title: 'NSFW Content', keywords: ['nsfw', 'blur', 'adult', 'content', 'filter', 'hide', 'show'] },
  { tab: 'wallet', title: 'Auto-Lock', keywords: ['auto', 'lock', 'timeout', 'inactivity', 'security'] },
  { tab: 'preferences', title: 'Notification Duration', keywords: ['toast', 'notification', 'duration', 'dismiss', 'alert'] },
  { tab: 'preferences', title: 'Desktop Notifications', keywords: ['desktop', 'notification', 'system', 'os', 'bid', 'alert'] },
  { tab: 'preferences', title: 'Notification Sounds', keywords: ['sound', 'notification', 'audio', 'volume', 'alert', 'ping', 'preview'] },
  { tab: 'wallet', title: 'Lock Wallet', keywords: ['lock', 'wallet', 'password'] },
  { tab: 'network', title: 'Network Selection', keywords: ['network', 'preprod', 'mainnet', 'switch', 'restart'] },
  { tab: 'datalayer', title: 'Iagon Decentralized Storage', keywords: ['iagon', 'storage', 'decentralized', 'api', 'key', 'upload', 'download', 'file', 'connect', 'verify', 'disconnect'] },
  { tab: 'datalayer', title: 'Storage Usage', keywords: ['iagon', 'storage', 'usage', 'bytes', 'files', 'total'] },
  { tab: 'datalayer', title: 'Orphaned Files', keywords: ['orphan', 'draft', 'cleanup', 'iagon', 'abandoned'] },
  { tab: 'storage', title: 'Disk Usage', keywords: ['disk', 'storage', 'space', 'chain', 'data', 'snark', 'size', 'breakdown', 'directory'] },
  { tab: 'storage', title: 'Image Cache', keywords: ['image', 'cache', 'clear', 'cached', 'thumbnail', 'banned'] },
  { tab: 'storage', title: 'API Response Cache', keywords: ['api', 'cache', 'response', 'clear', 'memory'] },
  { tab: 'storage', title: 'Transaction History', keywords: ['transaction', 'history', 'clear', 'cleanup', 'failed'] },
  { tab: 'logs', title: 'Process Logs', keywords: ['log', 'logs', 'process', 'stdout', 'stderr', 'search'] },
  { tab: 'logs', title: 'Developer Mode', keywords: ['debug', 'developer', 'config', 'localstorage', 'advanced', 'pid'] },
  { tab: 'automation', title: 'Auto-Accept Bids', keywords: ['auto', 'accept', 'automation', 'queue', 'bid', 'snark', 'reencrypt', 'background', 'processing', 'completed', 'failed'] },
  { tab: 'update', title: 'App Updates', keywords: ['update', 'version', 'upgrade', 'download', 'release', 'appimage', 'about', 'notes'] },
  { tab: 'contact', title: 'Contact & Support', keywords: ['contact', 'support', 'discord', 'email', 'help', 'about'] },
]
