// Copyright 2025-2026 Logical Mechanism LLC
// SPDX-License-Identifier: Apache-2.0

// circuit.go — GENERATED FILE
//
// This file is generated by Claude from the proof.pattern specification.
// It defines the circuit struct, the gnark Define() method, and the
// CLI integration functions (CircuitSetup, CircuitProve).
//
// To regenerate, prompt Claude: "Generate the circuit from proof.pattern"
package main

import "fmt"

// CircuitSetup compiles the circuit and runs trusted setup.
// Generated by Claude from proof.pattern.
func CircuitSetup(outDir string, force bool) error {
	return fmt.Errorf("no circuit defined yet — prompt Claude: \"Generate the circuit from proof.pattern\"")
}

// CircuitProve generates a Groth16 proof using the circuit.
// Generated by Claude from proof.pattern.
func CircuitProve(setupDir, outDir, inputFile string, test bool) error {
	return fmt.Errorf("no circuit defined yet — prompt Claude: \"Generate the circuit from proof.pattern\"")
}
